### ISSUE TITLE
Unrealistic output regardless of data used.

### ISSUE THREAD

**Issue by BrRoBo** [zaxxio/layered-neural-network#1]
Both this layered implementation and your earlier single layer use similar logic and produce the same output/issues.

Oddly, if you use virtually any number as predict data, the output still shows near 100% (ie: .999998...) regardless. I mean, you can use predict(51, 20) and still get similar results to the 4 XOR sets of numbers used in your example.  For example, go ahead and run it with these additional predicts...

        neuralNetwork.predict(5, 4);
        neuralNetwork.predict(33, 56);

result:
- Input : [5.0, 4.0] Predicted : [0.9994366700726042, 0.9999933662619231]
- Input : [33.0, 56.0] Predicted : [0.9997702883782552, 0.9999951338556543]

Likewise, changing the input and target data to any nonsensical random values of any lengths (with the network configured to match the shapes) will still produce the most amazing, near 100% prediction values.  Either there is a hidden Carnac the Magnificent embedded somewhere in the code, or more likely something overlooked in the implementation.

Comments?

**Comment by zaxxio** [comment]
It can happen because I have not used any normalization inside the library. You could create PR if you find any solutions. I am a bit busy right now to work on this. Thanks.
